force-app/main/default/objects/Time1__c/Time1__c.object-meta.xml
<CustomObject>
    <label>Time1</label>
    <nameField>
        <label>Time1 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Times1</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Time1__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Times1</relationshipLabel>
    <relationshipName>Times1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Time1TriggerTest.cls
@istest
public class Time1TriggerTest {
@istest
    
    public static void main(){
        
        contact c= new contact(Lastname='test');
        insert c;
        Time1__c tc= new Time1__c();
        tc.name='tast';
        tc.StartDate__c=date.newInstance(2022, 06, 06);
                tc.EndDate__c=date.newInstance(2022, 07, 06);
tc.Contact__c=c.id;
        insert tc;
        
    }
    
    
}