force-app/main/default/objects/Beer__c/Beer__c.object-meta.xml
<CustomObject>
    <label>Beer</label>
    <nameField>
        <label>Beer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Beers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Beer__c/fields/Alcohol__c.field-meta.xml
<CustomField>
    <fullName>Alcohol__c</fullName>
    <label>Alcohol %</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Beer__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/BeerClass.cls
public with sharing class BeerClass {

@AuraEnabled(cacheable=true)

public static list<Beer__c> getBeer(){
List<Beer__c> bc= [select id,name,price__c,Alcohol__c from Beer__c];
return bc ;

}

@AuraEnabled

public static list<Beer__c> searchBeer(string search){
string nam=search+'%';
List<Beer__c> bc= [select id,name,price__c,Alcohol__c from Beer__c where name like:nam];
return bc;

}

@AuraEnabled
public static void deleteBeer(id lst){
System.debug(' inside in methods '+lst);

List<Beer__c> del= [select id from Beer__c where id =:lst];
System.debug('size --> '+ del);
delete del;

}
}