force-app/main/default/objects/Event__c/fields/Event_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Event_Date_Time__c</fullName>
    <label>Event Date &amp; Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event_Participant__c/Event_Participant__c.object-meta.xml
<CustomObject>
    <label>Event Participant</label>
    <nameField>
        <displayFormat>EP-{000}</displayFormat>
        <label>Event Participant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Participant__c/fields/About_Contact__c.field-meta.xml
<CustomField>
    <fullName>About_Contact__c</fullName>
    <label>About Contact</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Attendee Contact</fullName>
            </value>
            <value>
                <fullName>Presenter Contact</fullName>
            </value>
            <value>
                <fullName>Organizer Contact&quot;</fullName>
                <label>Organizer Contact</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event_Participant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Event Participants</relationshipLabel>
    <relationshipName>Event_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Participant__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event Participants</relationshipLabel>
    <relationshipName>Event_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SS2task9.cls
public class SS2task9 {

    
    public static void task9(){
            List<id> conid=new List<id>();
        List<string> conname= new List<string>();
        List<Event_Participant__c> evpartlist=new List<Event_Participant__c>();

  Event__c ev=new Event__c(Name='Indipendance day', Event_Date_Time__c	=datetime.newInstance(2022, 08, 15, 13, 30, 00));
        insert ev;
        
        List<Contact> conlist=[Select id,name from Contact limit 10];
for(Contact co:conlist){
    conname.add(co.name);
        conid.add(co.id);   
    }
        
        for(integer i=0;i<=9;i++){
                    Event_Participant__c epobj=new Event_Participant__c();
					epobj.Contact__c=conid[i];
            epobj.name=conname[i];
            					epobj.Event__c=ev.id;
            if(i<=3){
                epobj.About_Contact__c='Attendee Contact';
            }
            else if(i>=4 && i<=7){
                epobj.About_Contact__c='Presenter Contact';
            }
            else if(i>7){
                epobj.About_Contact__c='Organizer Contact';
            }
            evpartlist.add(epobj);
            
        }
        insert evpartlist;    
        
    }    
}