force-app/main/default/objects/Flight__c/Flight__c.object-meta.xml
<CustomObject>
    <label>Flight</label>
    <nameField>
        <displayFormat>FLI-{0000}</displayFormat>
        <label>Flight Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Flight_passenger__c/Flight_passenger__c.object-meta.xml
<CustomObject>
    <label>Flight passenger</label>
    <nameField>
        <displayFormat>FP-{000}</displayFormat>
        <label>Flight passenger</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flight passengers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Flight_passenger__c/fields/DateOfDeparture__c.field-meta.xml
<CustomField>
    <fullName>DateOfDeparture__c</fullName>
    <label>DateOfDeparture</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Flight_passenger__c/fields/Flight__c.field-meta.xml
<CustomField>
    <fullName>Flight__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Flight</label>
    <referenceTo>Flight__c</referenceTo>
    <relationshipLabel>Flight passengers</relationshipLabel>
    <relationshipName>Flight_passengers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flight_passenger__c/fields/Passenger__c.field-meta.xml
<CustomField>
    <fullName>Passenger__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Passenger</label>
    <referenceTo>Passenger__c</referenceTo>
    <relationshipLabel>Flight passengers</relationshipLabel>
    <relationshipName>Flight_passengers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flight_passenger__c/fields/Section__c.field-meta.xml
<CustomField>
    <fullName>Section__c</fullName>
    <label>Section</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>First class</fullName>
            </value>
            <value>
                <fullName>Business class</fullName>
            </value>
            <value>
                <fullName>Economy class</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Passenger__c/Passenger__c.object-meta.xml
<CustomObject>
    <label>Passenger</label>
    <nameField>
        <label>Passenger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Passenger__c/fields/AgeGroup__c.field-meta.xml
<CustomField>
    <fullName>AgeGroup__c</fullName>
    <label>AgeGroup</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adult</fullName>
            </value>
            <value>
                <fullName>Child</fullName>
            </value>
            <value>
                <fullName>Infants</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BrainStorming2First.cls
public class BrainStorming2First {
    
    public static void main(){
        
        List<Passenger__c> addpass= new List<Passenger__c>();
        List<String> AgGroup= new List<String>{'Adult','Child','Infants'};
            List<integer> year= new List<integer>{1994,2019,2021};
                
                integer per=1;
        For(integer i=0;i<3;i++){                         
            for(integer j=0;j<3;j++){
                Passenger__c Newps= new Passenger__c();
                Newps.Name='BrainStorming2 '+per;
                Newps.DateOfBirth__c=date.newInstance(year[j], 5, 20).addMonths(j);
                Newps.AgeGroup__c=AgGroup[j]; 
                addpass.add(Newps);
                per++;   
            }   
        }
        insert addpass;
        
        List<Flight__c> addFlight= new  List<Flight__c>();
        
        for(integer F=0;f<3;f++){
            Flight__c flight= new Flight__c(capacity__C=20);
            addFlight.add(flight); 
        }
        insert addFlight;   
        
        List<String> Sections= new List<string>{'First class', 'Business class', 'Economy class'};
            List<Flight_passenger__c> FlightList= new List<Flight_passenger__c>();       
        
        integer increment=0;

        For(integer k=0;k<3;k++){             
            for(integer fp=0;fp<3;fp++){
                Flight_passenger__c NewFlightP= new Flight_passenger__c();
                
                NewFlightP.Flight__c=addFlight[k].id;
                NewFlightP.Passenger__c=addpass[increment].id;              
                NewFlightP.DateOfDeparture__c=date.today()+1;
                NewFlightP.Section__c=Sections[fp];
                FlightList.add(NewFlightP);  
                increment++;
            }  
        } 
        insert FlightList;   
    }   
}