force-app/main/default/objects/Flight__c/Flight__c.object-meta.xml
<CustomObject>
    <label>Flight</label>
    <nameField>
        <displayFormat>FLI-{0000}</displayFormat>
        <label>Flight Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Flight_passenger__c/Flight_passenger__c.object-meta.xml
<CustomObject>
    <label>Flight passenger</label>
    <nameField>
        <displayFormat>FP-{000}</displayFormat>
        <label>Flight passenger</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flight passengers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Flight_passenger__c/fields/DateOfDeparture__c.field-meta.xml
<CustomField>
    <fullName>DateOfDeparture__c</fullName>
    <label>DateOfDeparture</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Flight_passenger__c/fields/Flight__c.field-meta.xml
<CustomField>
    <fullName>Flight__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Flight</label>
    <referenceTo>Flight__c</referenceTo>
    <relationshipLabel>Flight passengers</relationshipLabel>
    <relationshipName>Flight_passengers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flight_passenger__c/fields/Passenger__c.field-meta.xml
<CustomField>
    <fullName>Passenger__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Passenger</label>
    <referenceTo>Passenger__c</referenceTo>
    <relationshipLabel>Flight passengers</relationshipLabel>
    <relationshipName>Flight_passengers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flight_passenger__c/fields/Section__c.field-meta.xml
<CustomField>
    <fullName>Section__c</fullName>
    <label>Section</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>First class</fullName>
            </value>
            <value>
                <fullName>Business class</fullName>
            </value>
            <value>
                <fullName>Economy class</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Passenger__c/Passenger__c.object-meta.xml
<CustomObject>
    <label>Passenger</label>
    <nameField>
        <label>Passenger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BrainStorming2SecondClass.cls
public class BrainStorming2SecondClass {
    
    Public static void main(List<Flight_passenger__c> NewFlight){
        map<id,Flight_passenger__c> FlightMap= new  map<id,Flight_passenger__c>();
        
        for(Flight_passenger__c FP:NewFlight){    
            FlightMap.put(FP.Passenger__c,FP);     
        }
        
        
// If passanger will book the same flight with different section whose date of departure is same, than the error will popup.
        
        List<Passenger__c> pslist=[select id,(select id,Flight__c,Section__c,dateOfDeparture__c from Flight_passengers__r) from Passenger__c where id in:FlightMap.keyset()];
        for(Passenger__c ps:pslist){
            for(Flight_passenger__c fligPass:ps.Flight_passengers__r){
                if(FlightMap.get(ps.id).id==fligPass.id && fligPass.Flight__c==FlightMap.get(ps.id).Flight__c &&
                   fligPass.dateOfDeparture__c==FlightMap.get(ps.id).dateOfDeparture__c){
                       
                       FlightMap.get(ps.id).addError('You have already booked the section in this flight! Now you can not change the section of this flight whose depature date is same'); 
                 }
            }
        }
    }    
}