force-app/main/default/objects/Maintenance__c/Maintenance__c.object-meta.xml
<CustomObject>
    <label>Maintenance</label>
    <nameField>
        <label>Maintenance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Maintenance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Maintenance__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Maintenance</relationshipLabel>
    <relationshipName>Maintenance</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AvgRatingTest.cls
@istest
public class AvgRatingTest {
@istest
    public static void main(){
        
        Contact con= new Contact(lastname='test');
        insert con;
         
        Maintenance__c m= new Maintenance__c();
        m.Contact__c=con.id;
        m.Name='test';
        m.Rating__c='5';
        insert m;
        
          Maintenance__c m2= new Maintenance__c();
        m2.Contact__c=con.id;
        m2.Name='test';
        m2.Rating__c='4';
        insert m2;
 
    }
}