force-app/main/default/objects/Daily_status__c/Daily_status__c.object-meta.xml
<CustomObject>
    <label>Daily status</label>
    <nameField>
        <displayFormat>DS-{0000}</displayFormat>
        <label>Daily status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_status__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Daily status</relationshipLabel>
    <relationshipName>Daily_status</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Daily_status__c/fields/Login_time__c.field-meta.xml
<CustomField>
    <fullName>Login_time__c</fullName>
    <label>Login time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Daily_status__c/fields/Logout_time__c.field-meta.xml
<CustomField>
    <fullName>Logout_time__c</fullName>
    <label>Logout time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/BrainNitin2Test.cls
@istest
public class BrainNitin2Test {
    @istest
    public static void main(){
        contact c =new Contact(Lastname='test');
        insert c;
        
        contact c1 =new Contact(Lastname='test2');
        insert c1;

        Daily_status__C ds= new Daily_status__C();
        ds.Login_time__c=datetime.now();
            ds.Logout_time__c=datetime.now()+1;
        ds.Contact__c=c.id;
        insert ds;
        
        Daily_status__C ds2= new Daily_status__C();
        ds2.Login_time__c=datetime.now();
            ds2.Logout_time__c=datetime.now()+1;
        ds2.Contact__c=c1.id;
        insert ds2;
        
        test.startTest();
        BrainNitin2.main();
        Test.stopTest();
    }
}