force-app/main/default/objects/Daily_status__c/Daily_status__c.object-meta.xml
<CustomObject>
    <label>Daily status</label>
    <nameField>
        <displayFormat>DS-{0000}</displayFormat>
        <label>Daily status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_status__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Daily status</relationshipLabel>
    <relationshipName>Daily_status</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Daily_status__c/fields/Time_interval__c.field-meta.xml
<CustomField>
    <fullName>Time_interval__c</fullName>
    <formula>( Logout_time__c - Login_time__c )*24*60</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Time interval</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BrainNitin2.cls
public class BrainNitin2 {

    public static void main(){
        List<decimal> inter= new List<decimal>();
       List<Daily_status__C> dslist=[select time_interval__C from Daily_status__C ]; 
       
        for(Daily_status__C ds:dslist){

inter.add(ds.time_interval__C);     
        }
        inter.sort();
       
    List<Daily_status__C> daily=[select contact__r.name,time_interval__C from Daily_status__C];
    for(Daily_status__C d:daily){
        if(d.time_interval__C==inter[0]){
            system.debug('Minimum time '+d.contact__r.name +' '+d.Time_interval__c+' Minutes');
        }
        if(d.time_interval__C==inter[inter.size()-1]){
            system.debug('Maximum time '+d.contact__r.name +' '+d.Time_interval__c+' Minutes');
        }
    }}
    
}